//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedFlix
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificaciones
    {
        public int ID { get; set; }
        public int perfilID { get; set; }
        public int tmdbID { get; set; }
        public string tipo { get; set; }
        public int puntaje { get; set; }
        public System.DateTime fechaCalificacion { get; set; }
    
        public virtual perfiles perfiles { get; set; }
    }
}
