//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedFlix
{
    using System;
    using System.Collections.Generic;
    
    public partial class clima
    {
        public int ID { get; set; }
        public System.DateTime fecha { get; set; }
        public int temperatura { get; set; }
        public string descripcionClima { get; set; }
        public string icono { get; set; }
    }
}
