USE [master]
GO

/****** Object:  Database [RedFlixII]    Script Date: 31/5/2026 19:03:00 ******/
CREATE DATABASE [RedFlixII]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RedFlixII', FILENAME = N'C:\Users\1507f\RedFlixII.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RedFlixII_log', FILENAME = N'C:\Users\1507f\RedFlixII_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RedFlixII].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RedFlixII] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RedFlixII] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RedFlixII] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RedFlixII] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RedFlixII] SET ARITHABORT OFF 
GO

ALTER DATABASE [RedFlixII] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [RedFlixII] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RedFlixII] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RedFlixII] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RedFlixII] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RedFlixII] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RedFlixII] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RedFlixII] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RedFlixII] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RedFlixII] SET  ENABLE_BROKER 
GO

ALTER DATABASE [RedFlixII] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RedFlixII] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RedFlixII] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RedFlixII] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RedFlixII] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RedFlixII] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RedFlixII] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RedFlixII] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RedFlixII] SET  MULTI_USER 
GO

ALTER DATABASE [RedFlixII] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RedFlixII] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RedFlixII] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RedFlixII] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RedFlixII] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RedFlixII] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RedFlixII] SET QUERY_STORE = ON
GO

ALTER DATABASE [RedFlixII] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [RedFlixII] SET  READ_WRITE 
GO

