//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedFlix
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RedFlixIIIEntities : DbContext
    {
        public RedFlixIIIEntities()
            : base("name=RedFlixIIIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<calificaciones> calificaciones { get; set; }
        public virtual DbSet<clima> clima { get; set; }
        public virtual DbSet<favoritos> favoritos { get; set; }
        public virtual DbSet<listaContenido> listaContenido { get; set; }
        public virtual DbSet<listas> listas { get; set; }
        public virtual DbSet<perfiles> perfiles { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<cotizaciones> cotizaciones { get; set; }
    }
}
